name: Java Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change to the desired JDK version
          distribution: 'adopt'  # Specify the distribution

      - name: Compile Java Code
        run: javac demo.java 

      - name: Run Java Program
        run: java demo  
      
      - name: Run Java Program and Check Output
        run: |
          output=$(java demo)
          if [[ "$output" == *"HelloWorld"* ]]; then
            echo "Output verification: PASSED"
          else
            echo "Output verification: FAILED"
            exit 1
          fi
